### ISSUE TITLE
cannot create serverless template

### ISSUE THREAD

**Issue by harrywang** [runpod-workers/worker-a1111#2]
I want to run WebUI API mode using Runpod serverless GPU using the image in this repo and cannot save template - any pointers?

Do you have a tutorial to show how to run WebUI API mode using Runpod?

Thanks!

https://www.runpod.io/console/serverless/user/templates

<img width="942" alt="Screenshot 2023-05-31 at 3 11 21 PM" src="https://github.com/runpod-workers/worker-a1111/assets/595772/6c7e28bd-6d0b-467c-a31c-0bc5bf88b72c">

**Comment by justinmerrell** [comment]
Did you build the docker image into your own repository?

**Comment by harrywang** [comment]
> Did you build the docker image into your own repository?

yes at https://hub.docker.com/r/harrywang/a1111-webui-api

**Comment by harrywang** [comment]
it did not work: see screencast - thanks for your help. 
https://github.com/runpod-workers/worker-a1111/assets/595772/3c198889-aa99-4e7c-a37c-ed0c77fe0734

**Comment by justinmerrell** [comment]
Oh, I see, you can't actually save the template. Are you able to inspect the page and then provide any console log errors you are seeing?

**Comment by harrywang** [comment]
here you go:
<img width="475" alt="Screenshot 2023-06-01 at 11 07 01 AM" src="https://github.com/runpod-workers/worker-a1111/assets/595772/3852f8ec-571f-449f-b1be-6afda85f49aa">

**Comment by justinmerrell** [comment]
Do you have a non-serverless template with the same name `a1111-webui-api` by any chance? Even if you do not, may you try again with a different template name?

**Comment by harrywang** [comment]
changed and name and it saved.
<img width="910" alt="Screenshot 2023-06-01 at 11 18 09 AM" src="https://github.com/runpod-workers/worker-a1111/assets/595772/063c57d1-9ab4-46da-b557-8cf7dd04f328">

**Comment by harrywang** [comment]
<img width="1757" alt="Screenshot 2023-06-01 at 11 32 32 AM" src="https://github.com/runpod-workers/worker-a1111/assets/595772/45a6c41c-4732-4121-b484-c9fb3bee2a75">

any idea on what's the endpoint for a1111 api? any pointers to tutorials or docs on this? thanks.

**Comment by justinmerrell** [comment]
As in, how to send requests? The endpoint URLs are the ones at the bottom `RUNSYNC`, `RUN`

**Comment by harrywang** [comment]
> As in, how to send requests? The endpoint URLs are the ones at the bottom `RUNSYNC`, `RUN`

for example, how to use the deployed api to generate an image using such as https://github.com/mix1009/sdwebuiapi

<img width="1052" alt="Screenshot 2023-06-04 at 4 13 06 PM" src="https://github.com/runpod-workers/worker-a1111/assets/595772/fce7dc73-65ab-474f-a654-7943820895ea">

**Comment by harrywang** [comment]
also I cannot see the /docs

https://api.runpod.ai/v2/kq3971qno2npoz/run/docs has nothing - this should be the api docs for the webui.

Thanks.

**Comment by harrywang** [comment]
> > As in, how to send requests? The endpoint URLs are the ones at the bottom `RUNSYNC`, `RUN`
> 
> for example, how to use the deployed api to generate an image using such as https://github.com/mix1009/sdwebuiapi
> 
> <img alt="Screenshot 2023-06-04 at 4 13 06 PM" width="1052" src="https://user-images.githubusercontent.com/595772/243204988-fce7dc73-65ab-474f-a654-7943820895ea.png">

@justinmerrell can you help please?

**Comment by justinmerrell** [comment]
> > > As in, how to send requests? The endpoint URLs are the ones at the bottom `RUNSYNC`, `RUN`
> > 
> > 
> > for example, how to use the deployed api to generate an image using such as https://github.com/mix1009/sdwebuiapi
> > <img alt="Screenshot 2023-06-04 at 4 13 06 PM" width="1052" src="https://user-images.githubusercontent.com/595772/243204988-fce7dc73-65ab-474f-a654-7943820895ea.png">
> 
> @justinmerrell can you help please?

Oh, I believe I see now. You Are trying to interface with the internal webui directly. If you wanted to do it that way you will need to deploy Automatic1111 as a standard pod. This is also why you are unable to access the docs URL. 

However, if you used this repository as is to launch an endpoint instead of sending the requests like you did [here ](https://github.com/runpod-workers/worker-a1111/issues/2#issuecomment-1575697095), you would be sending them to the endpoint directly via a HTTP request. Example:

```python 
import requests

url = "https://api.runpod.ai/v2/kq3971qno2npoz/runsync"

payload = {"input": {"prompt": "cute cat"}}
headers = {
    "accept": "application/json",
    "content-type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)

print(response.text)
```
