### ISSUE TITLE
CUDA drivers? 

### ISSUE THREAD

**Issue by jadechip** [runpod-workers/worker-a1111#8]
Is there a reason a base image with CUDA drivers is not used? Such as nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04?
Would be happy to create a PR. 
Thanks

**Comment by justinmerrell** [comment]
Just to keep the docker size down, the drivers are installed, and the final built image uses the GPU.

If there is a particular issue you are running into please provide additional information, PRs that offer improvements are always welcomed :)

**Comment by albicasty** [comment]
sorry, it is not clear for me how cuda drivers get installed.

I am trying to build the image with docker locally, but I am getting errors because the NVidia drivers are not found.

**Comment by albicasty** [comment]
![image](https://github.com/runpod-workers/worker-a1111/assets/20678234/36d2a3bd-19cf-41f0-b793-0e835e2ec640)
![image](https://github.com/runpod-workers/worker-a1111/assets/20678234/24da0234-f242-4385-9139-28e873c1d986)

These are some of the errors I get.
I am on ubuntu 22.04 with nvidia drivers installed.

**Comment by albicasty** [comment]
ok thansk for the clarification.

Yes, I get the error during the build:

![image](https://github.com/runpod-workers/worker-a1111/assets/20678234/aae91cfa-ee56-4909-972d-9fac4a6ebc52)


If I change RUN export COMMANDLINE_ARGS="--skip-torch-cuda-test --precision full --no-half" with
ARG COMMANDLINE_ARGS="--skip-torch-cuda-test --precision full --no-half

I dunno get anymore the error during the build

**Comment by justinmerrell** [comment]
Are you making changes to the repo or building from a clean clone? 

It looks like something needs those build time args vs the runtime args, but I'll consider this resolved since you have a resolution.
